- id: morning-routine
  alias: Morning Routine
  trigger:
    platform: webhook
    webhook_id: alarm
  action:
  - delay: '00:00:30'
  - service: media_player.volume_set
    entity_id: media_player.home_schlafzimmer
    data:
      volume_level: 0.3
  - service: tts.google_say
    entity_id: media_player.home_schlafzimmer
    data:
      message: Guten Morgen, Max
      language: de
  - service: media_player.play_media
    data:
      entity_id: media_player.mopidy
      media_content_id: Wecker
      media_content_type: playlist
  - service: media_player.volume_set
    entity_id: media_player.home_schlafzimmer
    data:
      volume_level: 0.1
  - service: script.stream_mopidy_to_cc
    data:
      entity_id: 'media_player.home_schlafzimmer'
  - delay: '00:00:30'
  - service: media_player.volume_set
    entity_id: media_player.home_schlafzimmer
    data:
      volume_level: 0.2
  - delay: '00:00:30'
  - service: media_player.volume_set
    entity_id: media_player.home_schlafzimmer
    data:
      volume_level: 0.3
  - delay: '00:00:30'
  - service: media_player.volume_set
    entity_id: media_player.home_schlafzimmer
    data:
      volume_level: 0.4
  - delay: '00:00:30'
  - service: media_player.volume_set
    entity_id: media_player.home_schlafzimmer
    data:
      volume_level: 0.5
      

- id: turn-off-light-when-leaving
  alias: Licht aus wenn weg
  trigger:
  - entity_id: device_tracker.pixel2xl
    platform: state
    from: home
    to: not_home
  action:
  - service: light.turn_off
    entity_id: group.all_lights

- id: tv-mode
  alias: Fernsehmodus aktivieren
  trigger:
  - entity_id: media_player.cast_fernseher
    platform: state
    to: 'playing'
  condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
  - service: scene.turn_on
    entity_id: scene.fernsehmodus

- id: daily-backup
  alias: Tägliches Backup um 4 Uhr
  trigger:
    platform: time
    at: '4:00:00'
  action:
  - service: hassio.addon_start
    data:
      addon: ce20243c_remote_backup

- id: letsencrypt-renewal
  alias: "Let's Encrypt Renewal"
  trigger:
  - platform: time
    at: '00:00:00'
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt